# Generated by Django 3.0.4 on 2020-04-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp39',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp3901', models.CharField(blank=True, max_length=20, null=True)),
                ('emp3902', models.CharField(blank=True, max_length=20, null=True)),
                ('emp3903', models.CharField(blank=True, max_length=1, null=True)),
                ('emp3904', models.CharField(blank=True, max_length=8, null=True)),
                ('emp3905', models.CharField(blank=True, max_length=4, null=True)),
                ('emp3906', models.CharField(blank=True, max_length=30, null=True)),
                ('emp3907', models.CharField(blank=True, max_length=30, null=True)),
                ('emp3908', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'emp39',
                'managed': True,
            },
        ),
    ]
