# Generated by Django 3.0.4 on 2020-04-06 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punch_work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineAccount',
            fields=[
                ('account', models.CharField(db_column='Account', max_length=50)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=50, null=True)),
                ('LineID', models.CharField(db_column='LineID', max_length=50, primary_key=True, serialize=False)),
                ('LineName', models.CharField(db_column='LineName', max_length=50)),
                ('LinePic', models.CharField(db_column='LinePic', max_length=200)),
            ],
            options={
                'db_table': 'LineAccount',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Workpunch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=10)),
                ('time', models.DateTimeField()),
                ('status', models.IntegerField()),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('ip', models.CharField(blank=True, max_length=20, null=True)),
                ('system', models.CharField(blank=True, max_length=100, null=True)),
                ('loc', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'WorkPunch',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Emp39',
        ),
    ]
