# Generated by Django 3.0.4 on 2020-04-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account', models.CharField(db_column='Account', max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, db_column='Password', max_length=50, null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=50, null=True)),
                ('purview', models.IntegerField(blank=True, db_column='Purview', null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True)),
                ('empid', models.CharField(blank=True, db_column='EmpId', max_length=8, null=True)),
                ('createdate', models.DateTimeField(blank=True, db_column='Createdate', null=True)),
                ('logindate', models.DateTimeField(blank=True, db_column='Logindate', null=True)),
            ],
            options={
                'db_table': 'Account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answerid', models.CharField(db_column='AnswerId', max_length=50, primary_key=True, serialize=False)),
                ('questionid', models.CharField(blank=True, db_column='QuestionId', max_length=50, null=True)),
                ('answerdstr', models.CharField(blank=True, db_column='AnswerDstr', max_length=3000, null=True)),
                ('answeracountid', models.CharField(blank=True, db_column='AnswerAcountId', max_length=50, null=True)),
                ('answerdate', models.DateTimeField(blank=True, db_column='AnswerDate', null=True)),
                ('doc', models.CharField(blank=True, db_column='Doc', max_length=3000, null=True)),
            ],
            options={
                'db_table': 'Answer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('loginid', models.CharField(db_column='LoginId', max_length=50, primary_key=True, serialize=False)),
                ('menuno', models.CharField(db_column='MenuNo', max_length=50)),
                ('permission', models.CharField(blank=True, db_column='Permission', max_length=50, null=True)),
                ('mark', models.CharField(blank=True, db_column='Mark', max_length=300, null=True)),
                ('class_field', models.CharField(db_column='class', max_length=2)),
                ('createdate', models.DateTimeField(blank=True, db_column='CreateDate', null=True)),
            ],
            options={
                'db_table': 'Authority',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Calendardata',
            fields=[
                ('calendardate', models.DateField(db_column='CalendarDate', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=1, null=True)),
            ],
            options={
                'db_table': 'CalendarData',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentid', models.CharField(db_column='DepartmentId', max_length=8, primary_key=True, serialize=False)),
                ('departmentname', models.CharField(blank=True, db_column='DepartmentName', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dialyworkrecord',
            fields=[
                ('dialyworkrecordid', models.CharField(db_column='DialyWorkRecordId', max_length=50, primary_key=True, serialize=False)),
                ('employeeid', models.CharField(blank=True, db_column='EmployeeId', max_length=8, null=True)),
                ('workdate', models.DateField(blank=True, db_column='WorkDate', null=True)),
                ('projectid', models.CharField(blank=True, db_column='ProjectId', max_length=50, null=True)),
                ('workitemid', models.CharField(blank=True, db_column='WorkItemId', max_length=8, null=True)),
                ('isovertime', models.CharField(blank=True, db_column='IsOverTime', max_length=1, null=True)),
                ('workhours', models.DecimalField(blank=True, db_column='WorkHours', decimal_places=1, max_digits=12, null=True)),
                ('workcontent', models.TextField(blank=True, db_column='WorkContent', null=True)),
            ],
            options={
                'db_table': 'DialyWorkRecord',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Emp39',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp3901', models.CharField(blank=True, max_length=20, null=True)),
                ('emp3902', models.CharField(blank=True, max_length=20, null=True)),
                ('emp3903', models.CharField(blank=True, max_length=1, null=True)),
                ('emp3904', models.CharField(blank=True, max_length=8, null=True)),
                ('emp3905', models.CharField(blank=True, max_length=4, null=True)),
                ('emp3906', models.CharField(blank=True, max_length=30, null=True)),
                ('emp3907', models.CharField(blank=True, max_length=30, null=True)),
                ('emp3908', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'emp39',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empid', models.CharField(db_column='EmpId', max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=50, null=True)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=300, null=True)),
                ('directdepartment', models.CharField(blank=True, db_column='DirectDepartment', max_length=8, null=True)),
                ('directsupervisor', models.CharField(blank=True, db_column='DirectSupervisor', max_length=8, null=True)),
                ('agent', models.CharField(blank=True, db_column='Agent', max_length=8, null=True)),
                ('postalcode1', models.CharField(blank=True, db_column='PostalCode1', max_length=5, null=True)),
                ('address1', models.CharField(blank=True, db_column='Address1', max_length=300, null=True)),
                ('postalcode2', models.CharField(blank=True, db_column='PostalCode2', max_length=5, null=True)),
                ('address2', models.CharField(blank=True, db_column='Address2', max_length=300, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=50, null=True)),
                ('mobile', models.CharField(blank=True, db_column='Mobile', max_length=50, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True)),
                ('createdate', models.DateTimeField(blank=True, db_column='Createdate', null=True)),
                ('modifydate', models.DateTimeField(blank=True, db_column='Modifydate', null=True)),
                ('onboarddate', models.DateField(blank=True, db_column='OnBoardDate', null=True)),
                ('quitdate', models.DateField(blank=True, db_column='QuitDate', null=True)),
            ],
            options={
                'db_table': 'Employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Leavedata',
            fields=[
                ('leaveno', models.CharField(db_column='LeaveNo', max_length=50, primary_key=True, serialize=False)),
                ('empid', models.CharField(blank=True, db_column='EmpId', max_length=8, null=True)),
                ('type', models.CharField(blank=True, max_length=4, null=True)),
                ('startdatetime', models.DateTimeField(blank=True, db_column='StartDateTime', null=True)),
                ('enddatetime', models.DateTimeField(blank=True, db_column='EndDateTime', null=True)),
                ('hours', models.DecimalField(blank=True, db_column='Hours', decimal_places=1, max_digits=12, null=True)),
                ('notificationobject', models.CharField(blank=True, db_column='NotificationObject', max_length=8000, null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=3, null=True)),
                ('signempid', models.CharField(blank=True, db_column='SignEmpId', max_length=8, null=True)),
                ('createdate', models.DateTimeField(blank=True, db_column='Createdate', null=True)),
                ('modifydate', models.DateTimeField(blank=True, db_column='Modifydate', null=True)),
                ('agent', models.CharField(blank=True, db_column='Agent', max_length=8, null=True)),
            ],
            options={
                'db_table': 'LeaveData',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Leavetype',
            fields=[
                ('leavetypeid', models.CharField(db_column='LeaveTypeId', max_length=8, primary_key=True, serialize=False)),
                ('leavename', models.CharField(blank=True, db_column='LeaveName', max_length=50, null=True)),
            ],
            options={
                'db_table': 'LeaveType',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('projectid', models.CharField(db_column='ProjectId', max_length=50, primary_key=True, serialize=False)),
                ('account', models.CharField(db_column='Account', max_length=8)),
                ('createdate', models.DateTimeField(blank=True, db_column='Createdate', null=True)),
                ('modifydate', models.DateTimeField(blank=True, db_column='Modifydate', null=True)),
            ],
            options={
                'db_table': 'Member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menuno', models.CharField(db_column='MenuNo', max_length=50, primary_key=True, serialize=False)),
                ('menuname', models.CharField(blank=True, db_column='MenuName', max_length=50, null=True)),
                ('menuaddress', models.CharField(blank=True, db_column='MenuAddress', max_length=300, null=True)),
                ('parent', models.CharField(blank=True, max_length=50, null=True)),
                ('layer', models.IntegerField(blank=True, null=True)),
                ('path', models.CharField(blank=True, max_length=8000, null=True)),
                ('mark', models.CharField(blank=True, db_column='Mark', max_length=300, null=True)),
                ('seqno', models.IntegerField(blank=True, db_column='SeqNo', null=True)),
                ('createdate', models.DateTimeField(blank=True, db_column='CreateDate', null=True)),
            ],
            options={
                'db_table': 'Menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Onbusinessdata',
            fields=[
                ('onbusinessno', models.CharField(db_column='OnBusinessNo', max_length=50, primary_key=True, serialize=False)),
                ('empid', models.CharField(blank=True, db_column='EmpId', max_length=8, null=True)),
                ('maincontent', models.CharField(blank=True, db_column='MainContent', max_length=1000, null=True)),
                ('startdatetime', models.DateTimeField(blank=True, db_column='StartDateTime', null=True)),
                ('enddatetime', models.DateTimeField(blank=True, db_column='EndDateTime', null=True)),
                ('hours', models.DecimalField(blank=True, db_column='Hours', decimal_places=1, max_digits=12, null=True)),
                ('notificationobject', models.CharField(blank=True, db_column='NotificationObject', max_length=8000, null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=3, null=True)),
                ('signempid', models.CharField(blank=True, db_column='SignEmpId', max_length=8, null=True)),
                ('createdate', models.DateTimeField(blank=True, db_column='Createdate', null=True)),
                ('modifydate', models.DateTimeField(blank=True, db_column='Modifydate', null=True)),
            ],
            options={
                'db_table': 'OnBusinessData',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Overtimedata',
            fields=[
                ('overtimeno', models.CharField(db_column='OvertimeNo', max_length=50, primary_key=True, serialize=False)),
                ('empid', models.CharField(blank=True, db_column='EmpId', max_length=8, null=True)),
                ('maincontent', models.CharField(blank=True, db_column='MainContent', max_length=1000, null=True)),
                ('startdatetime', models.DateTimeField(blank=True, db_column='StartDateTime', null=True)),
                ('enddatetime', models.DateTimeField(blank=True, db_column='EndDateTime', null=True)),
                ('hours', models.DecimalField(blank=True, db_column='Hours', decimal_places=1, max_digits=12, null=True)),
                ('notificationobject', models.CharField(blank=True, db_column='NotificationObject', max_length=8000, null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=3, null=True)),
                ('signempid', models.CharField(blank=True, db_column='SignEmpId', max_length=8, null=True)),
                ('createdate', models.DateTimeField(blank=True, db_column='Createdate', null=True)),
                ('modifydate', models.DateTimeField(blank=True, db_column='Modifydate', null=True)),
            ],
            options={
                'db_table': 'OvertimeData',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectid', models.CharField(db_column='ProjectId', max_length=50, primary_key=True, serialize=False)),
                ('projectname', models.CharField(blank=True, db_column='ProjectName', max_length=300, null=True)),
                ('startdate', models.DateTimeField(blank=True, db_column='Startdate', null=True)),
                ('scheduledenddate', models.DateTimeField(blank=True, db_column='ScheduledEnddate', null=True)),
                ('realenddate', models.DateTimeField(blank=True, db_column='RealEnddate', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=1, null=True)),
                ('account', models.CharField(blank=True, db_column='Account', max_length=8, null=True)),
                ('createdate', models.DateTimeField(blank=True, db_column='Createdate', null=True)),
                ('modifydate', models.DateTimeField(blank=True, db_column='Modifydate', null=True)),
            ],
            options={
                'db_table': 'Project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Projectfunction',
            fields=[
                ('projectid', models.CharField(db_column='ProjectId', max_length=50, primary_key=True, serialize=False)),
                ('functionid', models.CharField(db_column='FunctionId', max_length=50)),
                ('functionname', models.CharField(blank=True, db_column='FunctionName', max_length=300, null=True)),
                ('account', models.CharField(blank=True, db_column='Account', max_length=8, null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=2, null=True)),
                ('createdate', models.DateTimeField(blank=True, db_column='Createdate', null=True)),
                ('modifydate', models.DateTimeField(blank=True, db_column='Modifydate', null=True)),
            ],
            options={
                'db_table': 'ProjectFunction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('questionid', models.CharField(db_column='QuestionId', max_length=50, primary_key=True, serialize=False)),
                ('questionname', models.CharField(blank=True, db_column='QuestionName', max_length=300, null=True)),
                ('projectid', models.CharField(blank=True, db_column='ProjectId', max_length=50, null=True)),
                ('functionid', models.CharField(blank=True, db_column='FunctionId', max_length=50, null=True)),
                ('questiondstr', models.CharField(blank=True, db_column='QuestionDstr', max_length=3000, null=True)),
                ('doc', models.CharField(blank=True, db_column='Doc', max_length=3000, null=True)),
                ('sendid', models.CharField(blank=True, db_column='SendId', max_length=8, null=True)),
                ('senddate', models.DateTimeField(blank=True, db_column='SendDate', null=True)),
            ],
            options={
                'db_table': 'Question',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rockchip',
            fields=[
                ('seqno', models.AutoField(db_column='SeqNo', primary_key=True, serialize=False)),
                ('customer', models.CharField(blank=True, db_column='Customer', max_length=12, null=True)),
                ('product', models.CharField(blank=True, db_column='Product', max_length=10, null=True)),
                ('platform', models.CharField(blank=True, db_column='Platform', max_length=8, null=True)),
                ('android_ver', models.CharField(blank=True, db_column='Android_Ver', max_length=8, null=True)),
                ('android_codename', models.CharField(blank=True, db_column='Android_codename', max_length=6, null=True)),
                ('version_s', models.CharField(blank=True, db_column='Version_s', max_length=14, null=True)),
                ('version_e', models.CharField(blank=True, db_column='Version_e', max_length=14, null=True)),
                ('date', models.CharField(blank=True, db_column='Date', max_length=12, null=True)),
                ('variant', models.CharField(blank=True, db_column='Variant', max_length=5, null=True)),
                ('field_key', models.CharField(blank=True, db_column='_Key', max_length=10, null=True)),
            ],
            options={
                'db_table': 'Rockchip',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Workitem',
            fields=[
                ('workitemid', models.CharField(db_column='WorkItemId', max_length=8, primary_key=True, serialize=False)),
                ('workitemname', models.CharField(blank=True, db_column='WorkItemName', max_length=50, null=True)),
            ],
            options={
                'db_table': 'WorkItem',
                'managed': False,
            },
        ),
    ]
