# Generated by Django 3.0.4 on 2020-04-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineAccount',
            fields=[
                ('account', models.CharField(db_column='Account', max_length=50)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=50, null=True)),
                ('LineID', models.CharField(db_column='LineID', max_length=50, primary_key=True, serialize=False)),
                ('LineName', models.CharField(db_column='LineName', max_length=50)),
                ('LinePic', models.CharField(db_column='LinePic', max_length=200)),
            ],
            options={
                'db_table': 'LineAccount',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Authority',
        ),
        migrations.DeleteModel(
            name='Calendardata',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Dialyworkrecord',
        ),
        migrations.DeleteModel(
            name='Emp39',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Leavedata',
        ),
        migrations.DeleteModel(
            name='Leavetype',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Onbusinessdata',
        ),
        migrations.DeleteModel(
            name='Overtimedata',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Projectfunction',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Rockchip',
        ),
        migrations.DeleteModel(
            name='Workitem',
        ),
    ]
